### ISSUE TITLE
FileNotFoundError Error in FilterSig

### ISSUE THREAD

**Issue by Liangyan-1996** [zhaoweiyu-github/CondSig#2]
Hi Zhaowei,
Excellent job!
I downloaded the demo data (K562) and tested the pipeline. The **LearnSig** module worked well and I got appropriate ouput.
However, in the **FilterSig** module, I met a FileNotFoundError:
```
Traceback (most recent call last):
  File "/public/home/liunangroup/liangyan/software/miniconda3/envs/condsig_env/bin/condsig_detector", line 330, in <module>
    main()
  File "/public/home/liunangroup/liangyan/software/miniconda3/envs/condsig_env/bin/condsig_detector", line 98, in main
    sigFE = FilterSig.SigFE(args)
  File "/public/home/liunangroup/liangyan/software/miniconda3/envs/condsig_env/lib/python3.7/site-packages/CondSig/FilterSig.py", line 252, in __init__
...
FileNotFoundError: [Errno 2] No such file or directory: 'K562_dataset_meta.txt'
```
The **'K562_dataset_meta.txt** does existed in my current directory. It is required for the **LearnSig** module.

Looking forward to your help.

**Comment by zhaoweiyu-github** [comment]
Hi Yan,
Thanks for your interest!
I think you can just provide the same file as you provided in LearSig module.
